sudo: required
dist: bionic
language: csharp
solution: Marathon.sln
mono: none
dotnet: 3.1.100
stages:
  - build
  - test
jobs:
  include:
    - stage: build
      name: build solution
      script: dotnet restore && dotnet build
    - stage: test
      name: run tests
      script: cd Source/Marathon.Test && dotnet test
