language: csharp
os:
 - linux
 
sudo: required
solution: Marathon.sln
mono: none
dist: xenial
dotnet: 3.1.100

addons:
  apt:
    sources:
    - sourceline: 'deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-trusty-prod trusty main'
      key_url: 'https://packages.microsoft.com/keys/microsoft.asc'
    packages:
     - libunwind8

before_script:
 - sudo apt-get install dotnet-sdk-2.2
 - cd Source/Marathon.Library

script:
 - dotnet restore
 - dotnet build
